version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     ACCEPT_EULA: 'Y'
     SA_PASSWORD: Password1234*
    ports:
      - '9991:1433'
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
